my version of homebridge script

diff --git a/scripts/homebridge b/scripts/homebridge
--- a/scripts/homebridge
+++ b/scripts/homebridge
@@ -1,40 +1,98 @@
 #!/bin/sh
 ### BEGIN INIT INFO
-# Provides:          homebridge
-# Required-Start:    $remote_fs dbus garage-door-gpio
-# Required-Stop:     $remote_fs dbus
-# Should-Start:	     $syslog
-# Should-Stop:       $syslog
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: Starts HomeBridge
-# Description:       Starts HomeBridge
+# Provides: homebridge
+# Required-Start: $network $remote_fs $syslog
+# Required-Stop: $remote_fs $syslog
+# Default-Start: 2 3 4 5
+# Default-Stop: 0 1 6
+# Short-Description: Start daemon at boot time
+# Description: Enable service provided by daemon.
 ### END INIT INFO
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DESC="Starts up HomeBridge (HomeKit Bridge)"
-NAME="homebridge"
-SCRIPTNAME=/etc/init.d/$NAME
+dir="/home/pi"
+cmd="DEBUG=* /usr/bin/homebridge"
+user="pi"
 
-. /lib/lsb/init-functions
+name=`basename $0`
+pid_file="/var/run/$name.pid"
+stdout_log="/var/log/$name.log"
+stderr_log="/var/log/$name.err"
+
+get_pid() {
+    cat "$pid_file"
+}
+
+is_running() {
+    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
+}
 
 case "$1" in
     start)
-        log_daemon_msg "Starting $NAME"
-
-	/usr/local/bin/homebridge -U /home/pi/.homebridge 2>&1 | /usr/sbin/rotatelogs /home/pi/.homebridge/homebridge.log.%y%m%d.%s 250M &
- 
-        log_end_msg $?
-        ;;
+    if is_running; then
+        echo "Already started"
+    else
+        echo "Starting $name"
+        cd "$dir"
+        if [ -z "$user" ]; then
+            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
+        else
+            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
+        fi
+        echo $! > "$pid_file"
+        if ! is_running; then
+            echo "Unable to start, see $stdout_log and $stderr_log"
+            exit 1
+        fi
+    fi
+    ;;
     stop)
-	log_daemon_msg "Stopping $NAME"
-        pkill homebridge
-        log_end_Msg $?
-        ;;
-    *)
-        echo "Usage: $SCRIPTNAME {start}" >&2
+    if is_running; then
+        echo -n "Stopping $name.."
+        kill `get_pid`
+        for i in {1..10}
+        do
+            if ! is_running; then
+                break
+            fi
+
+            echo -n "."
+            sleep 1
+        done
+        echo
+
+        if is_running; then
+            echo "Not stopped; may still be shutting down or shutdown may have failed"
+            exit 1
+        else
+            echo "Stopped"
+            if [ -f "$pid_file" ]; then
+                rm "$pid_file"
+            fi
+        fi
+    else
+        echo "Not running"
+    fi
+    ;;
+    restart)
+    $0 stop
+    if is_running; then
+        echo "Unable to stop, will not attempt to start"
         exit 1
-        ;;
+    fi
+    $0 start
+    ;;
+    status)
+    if is_running; then
+        echo "Running"
+    else
+        echo "Stopped"
+        exit 1
+    fi
+    ;;
+    *)
+    echo "Usage: $0 {start|stop|restart|status}"
+    exit 1
+    ;;
 esac
 
 exit 0
